{
 "title": "Benchmarking",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "1 app gunicorn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.tp1_gunicorn_1.cpu_usage_user)"
    },
    {
     "target": "stats.gauges.cadvisor.tp1_gunicorn_1.memory_usage"
    }
   ]
  },
  {
   "title": "Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.tp1_node_1.cpu_usage_user)"
    },
    {
     "target": "stats.gauges.cadvisor.tp1_node_1.memory_usage"
    }
   ]
  },
  {
   "title": "1/3 instancias gunicorn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.tp1_n-gunicorn_1.cpu_usage_user)"
    },
    {
     "target": "stats.gauges.cadvisor.tp1_n-gunicorn_1.memory_usage"
    }
   ]
  },
  {
   "title": "2/3 instancias gunicorn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.tp1_n-gunicorn_2.cpu_usage_user)"
    },
    {
     "target": "stats.gauges.cadvisor.tp1_n-gunicorn_2.memory_usage"
    }
   ]
  },
  {
   "title": "3/3 instancias gunicorn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "derivative(stats.gauges.cadvisor.tp1_n-gunicorn_3.cpu_usage_user)"
    },
    {
     "target": "stats.gauges.cadvisor.tp1_n-gunicorn_3.memory_usage"
    }
   ]
  }
 ]
}