{
 "title": "Heavy endpoint",
 "time": { "from": "2018-05-17T14:24:26.378Z", "to": "2018-05-17T14:26:49.365Z" },
 "panels": [
  {
   "title": "1 worker gunicorn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(derivative(stats.gauges.cadvisor.tp1_gunicorn_1.cpu_cumulative_usage), 1e-8), 'CPU')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.tp1_gunicorn_1.memory_usage, 'Memory')"
    }
   ]
  },
  {
   "title": "1 worker node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(derivative(stats.gauges.cadvisor.tp1_node_1.cpu_cumulative_usage), 1e-8), 'CPU')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.tp1_node_1.memory_usage, 'Memory')"
    }
   ]
  },
  {
   "title": "3 workers gunicorn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(derivative(stats.gauges.cadvisor.tp1_w-gunicorn_1.cpu_cumulative_usage), 1e-8), 'CPU')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.tp1_w-gunicorn_1.memory_usage, 'Memory')"
    }
   ]
  },
  {
   "title": "3 workers node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(derivative(stats.gauges.cadvisor.tp1_node-cluster_1.cpu_cumulative_usage), 1e-8), 'CPU')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.tp1_node-cluster_1.memory_usage, 'Memory')"
    }
   ]
  },
  {
   "title": "1/3 instancias gunicorn",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(derivative(stats.gauges.cadvisor.tp1_n-gunicorn_1.cpu_cumulative_usage), 5e-9), 'CPU')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.tp1_n-gunicorn_1.memory_usage, 'Memory')"
    }
   ]
  },
  {
   "title": "2/3 instancias gunicorn",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(derivative(stats.gauges.cadvisor.tp1_n-gunicorn_2.cpu_cumulative_usage), 5e-9), 'CPU')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.tp1_n-gunicorn_2.memory_usage, 'Memory')"
    }
   ]
  },
  {
   "title": "3/3 instancias gunicorn",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(derivative(stats.gauges.cadvisor.tp1_n-gunicorn_3.cpu_cumulative_usage), 5e-9), 'CPU')"
    },
    {
     "target": "alias(stats.gauges.cadvisor.tp1_n-gunicorn_3.memory_usage, 'Memory')"
    }
   ]
  }
 ]
}