version: '2'
services:

    gunicorn:
        build:
            context: .
            dockerfile: gunicorn.dockerfile
        volumes:
            - ./py:/app/py
        links:
            - grafana
        command: gunicorn -w 1 app:app -b :8000 --access-logfile access.log --error-logfile error.log --log-file=-

    w-gunicorn:
        build:
            context: .
            dockerfile: gunicorn.dockerfile
        volumes:
            - ./py:/app/py
        links:
            - grafana
        command: gunicorn -w 5 app:app -b :8000

    n-gunicorn:
        build:
            context: .
            dockerfile: gunicorn.dockerfile
        volumes:
            - ./py:/app/py
        links:
            - grafana
        command: gunicorn -w 1 app:app -b :8000 --access-logfile access-n.log --error-logfile error-n.log --log-file=-

    node:
        build:
            context: .
            dockerfile: node-express.dockerfile
        volumes:
            - ./js/src:/app/src
        links:
            - grafana
        command: npm run start

    cluser-node:
        build:
            context: .
            dockerfile: node-express.dockerfile
        volumes:
            - ./js/src/multiple_app.js:/app/src/app.js
        links:
            - grafana
        command: npm run start

    nw-gunicorn:
        build:
            context: .
            dockerfile: gunicorn.dockerfile
        volumes:
            - ./py:/app/py
        links:
            - grafana
        command: gunicorn -w 5 app:app -b :8000


    nginx:
        image: nginx:1.13.10
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - gunicorn
            - node

    graphite:
        image: graphiteapp/graphite-statsd:1.1.3
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:5.0.4
        ports:
            - "80:3000"

    cadvisor:
        image: google/cadvisor:v0.27.4
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"
